namespace Hkmp.Game.Client.Entity; 

/// <summary>
/// Enumeration of entity types. The entries more closely resemble the canonical name rather than the internal naming.
/// </summary>
internal enum EntityType {
    Crawlid = 0,
    Tiktik,
    Vengefly,
    WanderingHusk,
    HuskBully,
    HuskHornhead,
    Gruzzer,
    BattleGate,
    AspidHunter,
    HuskGuard,
    LeapingHusk,
    AspidMother,
    AspidHatchling,
    HuskWarrior,
    Goam,
    Baldur,
    ElderBaldur,
    FalseKnight,
    FalseKnightHead,
    FalseKnightBarrels,
    FalseKnightFloor,
    GruzMother,
    BroodingMawlek,
    BroodingMawlekArm,
    BroodingMawlekHead,
    BroodingMawlekDummy,
    Mosscreep,
    Mosskin,
    VolatileMosskin,
    FoolEater,
    Squit,
    Obble,
    Gulka,
    Durandoo,
    Duranda,
    MassiveMossCharger,
    MossCharger,
    MossKnight,
    Aluba,
    VengeflyKing,
    VengeflySummon,
    ChargedLumafly,
    Hornet,
    Uoma,
    Ooma,
    OomaCorpse,
    OomaCore,
    Ambloom,
    Fungling,
    Fungoon,
    Sporg,
    FungifiedHusk,
    Shrumeling,
    ShrumalWarrior,
    MantisYouth,
    MantisWarrior,
    MantisThrone,
    MantisLordBattle,
    MantisLord,
    MantisLordCage,
    MantisLordFloor
}
